name: 'Automatic version updates'

on:
  schedule:
    # hourly
    - cron: '00 * * * *'
  # enable manual trigger of version updates
  workflow_dispatch:
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: zopencommunity/meta/actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.BUMP_TOKEN }}
